-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 101835 2021
-- Model New Model    Version 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema snekDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema snekDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `snekDatabase` DEFAULT CHARACTER SET utf8 ;
USE `snekDatabase` ;

-- -----------------------------------------------------
-- Table `snekDatabase`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snekDatabase`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(15) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snekDatabase`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snekDatabase`.`scores` (
  `scores` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`scores`),
  INDEX `fk_scores_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_scores_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `snekDatabase`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
